### ISSUE TITLE
I need helpibg for - Etherscan-api

### ISSUE THREAD

**Issue by Dferdi1199** [corpetty/py-etherscan-api#12]
Corpetty/py-etherscan-api

**Comment by RAHALIMEHREZ** [comment]
[about_blank.pdf](https://github.com/corpetty/py-etherscan-api/files/1483513/about_blank.pdf)

**Comment by corpetty** [comment]
Can you be more specific?

**Comment by nikwelcom** [comment]
Whot

**Comment by corpetty** [comment]
Closing this.  Open a new one if you have some specifics.
