### ISSUE TITLE
Documentations - API etherscan

### ISSUE THREAD

**Issue by gg4u** [corpetty/py-etherscan-api#18]
How to query for token holders (e.g. 
https://etherscan.io/token/tokenholderchart/<token>?range=500)

and by address
https://etherscan.io/address/<address>

**Comment by corpetty** [comment]
Currently, the Etherscan API does not allow for querying of token holders, as can be seen from their API documentation here: https://etherscan.io/apis#tokens.

They newer version of the token API deprecated the way the package currently works.  I'll refactor it to account for their changes and then you'll be able to query an address' balance with respect a particular token as long as you also know the token's smart contract address.  I'll reference the PR when I merge it in.

**Comment by corpetty** [comment]
recent commit changed to allow getting address balances from a token contract.  See the `/examples/tokens` folder for examples.
