### ISSUE TITLE
Adding In Exceptions

### ISSUE THREAD

**Issue by taylorjdawson** [corpetty/py-etherscan-api#19]
https://github.com/corpetty/py-etherscan-api/blob/a36885b66f6ca96f204f4994edb742c31334a246/etherscan/client.py#L78-L99

I think it would be a good idea to throw exceptions instead of printing error messages and then exiting. For instance, if the user was to loop over a list of addresses to check the balance but there were some invalid addresses in the list, as of now, the api would break the loop. Throwing exceptions will enable the user to catch and handle the exceptions themselves.

**Comment by AndreMiras** [comment]
I second this, a library should not make exit in the middle of the code, but let the application using the library handling it.
Here's a pull request that solves it.
https://github.com/corpetty/py-etherscan-api/pull/23
