### ISSUE TITLE
Unit testing

### ISSUE THREAD

**Issue by taylorjdawson** [corpetty/py-etherscan-api#20]
Under the TODOs you mention a unit test suite. Are you looking for unit tests beyond just assert statements? So using something like [Python unittest module](https://docs.python.org/3.6/library/unittest.html)? Currently, there are only a few unit tests so before I add more I wanted to know which direction you'd like to go.

**Comment by nikwelcom** [comment]
Оооол

**Comment by nikwelcom** [comment]
Вот

**Comment by AndreMiras** [comment]
Well I would recommend the built in Python unit test module.
I would also recommend using `tox` to try different Python versions and other things, like PEP8 compliance.
And last but not least setting some integration testing.
I can help with all these topics if you give me a go.

**Comment by corpetty** [comment]
You certainly have a go on that one, and I agree with @AndreMiras on the route.

**Comment by AndreMiras** [comment]
Great here is the first pull request that brings tox and Travis all together https://github.com/corpetty/py-etherscan-api/pull/29
This is the first of a long serie, in next ones I would like to:

1. drop `pytest` requirement and rely on core unittest module (you can still use the `pytest` command for testing locally if you like it)
2. integrate linter checks and fix lint errors
3. increase test coverage (maybe later)

**Comment by corpetty** [comment]
you can drop pytest completely.  unittest works just fine for all.  I have no preference.

**Comment by AndreMiras** [comment]
point 1 is fixed in https://github.com/corpetty/py-etherscan-api/issues/32 @corpetty can you merge so I tackle point 2
