### ISSUE TITLE
Broken proxy module

### ISSUE THREAD

**Issue by AndreMiras** [corpetty/py-etherscan-api#32]
Using the proxy module would fail with a `etherscan.client.EmptyResponse`.
This is because [Client.connect()](https://github.com/corpetty/py-etherscan-api/blob/54a7283/etherscan/client.py#L117) is expecting `data.get('status') == '1'` which is not the case for the proxy module.
See https://api.etherscan.io/api?module=proxy&action=eth_blockNumber&apikey=YourApiKeyToken for example returns:
```
{"jsonrpc":"2.0","id":83,"result":"0x56c811"}
```

**Comment by corpetty** [comment]
The recent pull requests #35 seems to fix this, if no one needs python 2.7 it can be merged.

**Comment by AndreMiras** [comment]
If you guys drop Python2 support, then think about updating the tox file so integration tests stay green.

**Comment by corpetty** [comment]
dropped, closed.
