### ISSUE TITLE
Use fstrings

### ISSUE THREAD

**Issue by taylorjdawson** [corpetty/py-etherscan-api#36]
Fstrings = syntatic surgar + speed.

How do you guys feel about switching `.formats` and ` % ` to fstrings?

**Comment by AndreMiras** [comment]
I love fstring but it's only from Python 3.6, so it means we don't even support Python 3.5? It might be a bit too much for a library no? Unless we have it available `from __future__`.

**Comment by corpetty** [comment]
While I also love fstrings, I'd like to make sure its compatible to at least 3.5.  Many people still use that.

**Comment by AndreMiras** [comment]
Yes I've read about it, but the author himself said it was hacky. It's tagged `hack` in GitHub and he said it's "terrible" on Stackoverflow https://stackoverflow.com/a/46225926/185510.
