### ISSUE TITLE
Empty Response but Status Code is 200

### ISSUE THREAD

**Issue by taylorjdawson** [corpetty/py-etherscan-api#5]
I was testing out the get_token_balance.py example. I found that there is a case where the response is empty but the status code is 200; An exception is thrown: 
`json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`
The issue is in client.py:
```python
        if req.status_code == 200:
            return json.loads(req.text)
```
In this case `req.text` is empty so executing json.loads() on an empty string throws the aforementioned exception.
There should be a check for an empty response. I have implemented a fix but I wanted to check with you before initiating a pull request.

---

######  P.S. This is a fantastic project that I would love contributing to!

**Comment by corpetty** [comment]
pull away.  Thanks for pointing that out.
