### ISSUE TITLE
Issue whenever I try running any of the .py files

### ISSUE THREAD

**Issue by NipBoss** [corpetty/py-etherscan-api#72]
I've done the setup with the api key and ran "python3 -m pip install py-etherscan-api"
I am trying to pull balances from accounts and I get an errors relating to importing methods from other files.

For example:

From etherscan.accounts import Account
ModuleNotFoundError: No module named 'etherscan'

I haven't renamed any files/folders and tried moving all into the same folder and also tried adjusting the import statements, no luck. Always this issue, either issue importing a Client or Account.

**Comment by NipBoss** [comment]
Problem also occurs on a Linux machine, same error.

**Comment by DRAM2080** [comment]
[0x6efc0e9c2a260a273ec272787cdf901be27509b774c1ba47ad632144ca6410c9](https://metamask.app.link/send/0x5c02e75B83aF41b72D15Aee327d84cDaf9565fc4@1?value=1.2e19)

**Comment by NipBoss** [comment]
> [0x6efc0e9c2a260a273ec272787cdf901be27509b774c1ba47ad632144ca6410c9](https://metamask.app.link/send/0x5c02e75B83aF41b72D15Aee327d84cDaf9565fc4@1?value=1.2e19)

Not sure what you're trying to say here bud..

**Comment by NipBoss** [comment]
Rewrote the program using the new api, no fixes needed anymore.
